spring:
  datasource:
    url: jdbc:h2:file:~/h2db/mydatabase
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

token:
  expire:
    time: 3600000  # 1시간 (밀리초)

kakao:
  map:
    api-key: "6ee40960f56c83c4e7d4c2e6e3dacd0f"